// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbn8JD3caAqjPefPwi7QbBptJJhPTMSHA',
    appId: '1:964894653817:web:cad41eed30cba7acf503a8',
    messagingSenderId: '964894653817',
    projectId: 'storex-74954',
    authDomain: 'storex-74954.firebaseapp.com',
    storageBucket: 'storex-74954.appspot.com',
    measurementId: 'G-XBJHFMYHMY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOWzyJtsoF1mM5g-c0ObRLWSMKYCFRXi4',
    appId: '1:964894653817:android:a8413382b236dae7f503a8',
    messagingSenderId: '964894653817',
    projectId: 'storex-74954',
    storageBucket: 'storex-74954.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB598CmoGvV-xATkt3tZkTlHP7t47OLUKQ',
    appId: '1:964894653817:ios:1fe145cc8579d22af503a8',
    messagingSenderId: '964894653817',
    projectId: 'storex-74954',
    storageBucket: 'storex-74954.appspot.com',
    androidClientId: '964894653817-ldl9r0856judcoabsp684rbcbr7kqnj6.apps.googleusercontent.com',
    iosClientId: '964894653817-10gmkbipjrlbu36dbg693hks4c3rkk5q.apps.googleusercontent.com',
    iosBundleId: 'com.example.giltezy2ndproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB598CmoGvV-xATkt3tZkTlHP7t47OLUKQ',
    appId: '1:964894653817:ios:a8df78e0c7ac2997f503a8',
    messagingSenderId: '964894653817',
    projectId: 'storex-74954',
    storageBucket: 'storex-74954.appspot.com',
    androidClientId: '964894653817-ldl9r0856judcoabsp684rbcbr7kqnj6.apps.googleusercontent.com',
    iosClientId: '964894653817-uqiegir40vf6sngti6gg3p4sc5rug3ph.apps.googleusercontent.com',
    iosBundleId: 'com.example.giltezy2ndproject.RunnerTests',
  );
}
